= Programação Funcional, Expressões Lambda e Streams no Java 17

Este é projeto que deve servir de base para você praticar programação funcional em Java com Streams e Lambdas.
Implemente seu código na classe `AppProgramacaoFuncional`, que está praticamente vazia. Ela usa a classe `StudentGenerator`
para gerar estudantes aleatoriamente. Assim, você tem dados para poder brincar.

O código completo dos exemplos está disponível em http://github.com/manoelcampos/programacao-funcional-java.

== 1. Como usar o projeto para treinar programação funcional

Este repositório é um template que você pode copiar clicando no botão "Fork" no topo da página.
Assim, será criada uma cópia do repositório que você pode alterar como desejado.
**O botão só aparece se você estiver logado no GitHub.**

== 2. Ferramentas recomendadas

- JDK 17 ou superior
- IntelliJ IDE

== 3. Baixar o JavaDoc do JDK e de bibliotecas utilizadas

- Abra um terminal na pasta raiz do projeto
- No Linux ou macOS digite: `./mvnw dependency:resolve -Dclassifier=javadoc`
- No Windows digite: `mvnw.cmd dependency:resolve -Dclassifier=javadoc`

== 4. Exercícios

Para todos os exercícios, leia todo o JavaDoc disponível na classe indicada, que contém instruções. Adicionalmente, procure por comentários iniciando em `TODO`, que contém indicações de partes do código que você **PRECISA** alterar.

=== Aula 01 (projeto externo)

- https://github.com/manoelcampos/fp-aula-01-soma-dobro-pares-js[Soma do dobro dos números pares]

=== Aula 02 (projeto externo)

- https://github.com/manoelcampos/fp-aula-02-imutabilidade-java[Praticando Imutabilidade em Java]

=== Aula 04

Abra a classe link:src/main/java/exercicios/Aula04.java[Aula04.java] e implemente os métodos disponíveis lá. Tais métodos devem ser implementados utilizando Streams e Lambdas. O nome da função deixa claro o que a função deve fazer.

=== Aula 06

Abra a classe link:src/main/java/exercicios/Aula06.java[Aula06.java] e implemente os métodos disponíveis lá. Tais métodos devem ser implementados utilizando Streams e Lambdas.

== 5. Projetos para serem desenvolvidos

- https://github.com/manoelcampos/fp-projeto-1-poligonos-flatmap[Um projeto base em OpenJFX para desenhar polígonos na tela e permitir a implementação de algumas funções para descobrir o tipo de cada polígono e calcular seu perímetro usando Stream.map e Stream.flatMap]


